### ISSUE TITLE
Crash (FPE) in check_hip.exe on LUMI

### ISSUE THREAD

**Issue by valassi** [madgraph5/madgraph4gpu#1003]
I am running tests of AMD GPUs on LUMI #998 

I am getting a new very bizarre crash
```
[valassia@nid007963 bash] ~/GPU2024/madgraph4gpu/epochX/cudacpp > gdb --args /users/valassia/GPU2024/madgraph4gpu/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/build.hip_d_inl0_hrd0/check_hip.exe --common -p 2 64 2
GNU gdb (GDB; SUSE Linux Enterprise 15) 12.1
...
Reading symbols from /users/valassia/GPU2024/madgraph4gpu/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/build.hip_d_inl0_hrd0/check_hip.exe...
(gdb) set style enabled off
(gdb) run
...
Thread 1 "check_hip.exe" received signal SIGFPE, Arithmetic exception.
0x0000155555508473 in mg5amcGpu::EventStatistics::operator+=(mg5amcGpu::EventStatistics const&) () from /pfs/lustrep3/scratch/project_465001114/valassia/GPU2024/madgraph4gpu/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/build.hip_d_inl0_hrd0/../../../lib/build.hip_d_inl0_hrd0/libmg5amc_gg_ttx_hip.so
Missing separate debuginfos, use: zypper install comgr-debuginfo-2.6.0.60003-sles154.131.x86_64 hip-runtime-amd-debuginfo-6.0.32831.60003-sles154.131.x86_64 hsa-rocr-debuginfo-1.12.0.60003-sles154.131.x86_64 libdrm2-debuginfo-2.4.114-150500.3.2.x86_64 libdrm_amdgpu1-debuginfo-2.4.114-150500.3.2.x86_64 libelf1-debuginfo-0.185-150400.5.3.1.x86_64 libgcc_s1-debuginfo-13.2.1+git7813-150000.1.6.1.x86_64 libncurses6-debuginfo-6.1-150000.5.20.1.x86_64 libnuma1-debuginfo-2.0.14.20.g4ee5e0c-150400.1.24.x86_64 libstdc++6-debuginfo-13.2.1+git7813-150000.1.6.1.x86_64 libz1-debuginfo-1.2.13-150500.4.3.1.x86_64 libzstd1-debuginfo-1.5.0-150400.3.3.1.x86_64
(gdb) where
#0  0x0000155555508473 in mg5amcGpu::EventStatistics::operator+=(mg5amcGpu::EventStatistics const&) ()
   from /pfs/lustrep3/scratch/project_465001114/valassia/GPU2024/madgraph4gpu/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/build.hip_d_inl0_hrd0/../../../lib/build.hip_d_inl0_hrd0/libmg5amc_gg_ttx_hip.so
#1  0x000015555550810d in mg5amcGpu::CrossSectionKernelHost::updateEventStatistics(bool) ()
   from /pfs/lustrep3/scratch/project_465001114/valassia/GPU2024/madgraph4gpu/epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/build.hip_d_inl0_hrd0/../../../lib/build.hip_d_inl0_hrd0/libmg5amc_gg_ttx_hip.so
#2  0x000000000021517c in main ()
```

**Comment by valassi** [comment]
And... this is yet another FPE crash that disappears in debug mode. I will add another volatile, most likely, but this is becoming too much.

**Comment by valassi** [comment]
Ok this magically fixes it
```
    // Combine two EventStatistics                                                                                                          
#if __HIP_CLANG_ONLY__
    // Disable optimizations for this function in HIPCC (work around FPE crash #1003)                                                       
    // See https://clang.llvm.org/docs/LanguageExtensions.html#extensions-for-selectively-disabling-optimization                            
    __attribute__((optnone))
#endif
    EventStatistics& operator+=( const EventStatistics& stats )
    {
```

**Comment by valassi** [comment]
This is fixed in PR #1006. Closing
