### ISSUE TITLE
Support for non-SM UFO models: code generation fails in model EWdim6

### ISSUE THREAD

**Issue by zeniheisser** [madgraph5/madgraph4gpu#615]
Generic issue: processes in non-SM models are not always supported (see also #614 )

Specific issue: non-SM UFO models lack support, even outputting more exotic models (eg EWdim6)

```
import model EWdim6
generate u d~ > w+ z
output standalone_cudacpp
Traceback (most recent call last):
  File "/data/zwetters/modded5amc/madgraph/interface/extended_cmd.py", line 1544, in onecmd
    return self.onecmd_orig(line, **opt)
  File "/data/zwetters/modded5amc/madgraph/interface/extended_cmd.py", line 1493, in onecmd_orig
    return func(arg, **opt)
  File "/data/zwetters/modded5amc/madgraph/interface/master_interface.py", line 299, in do_output
    self.cmd.do_output(self, line, *args, **opts)
  File "/data/zwetters/modded5amc/madgraph/interface/madgraph_interface.py", line 8324, in do_output
    self.finalize(nojpeg, flaglist=flaglist)
  File "/data/zwetters/modded5amc/madgraph/interface/madgraph_interface.py", line 8698, in finalize
    self._curr_exporter.convert_model(self._curr_model,
  File "/data/zwetters/modded5amc/PLUGIN/CUDACPP_SA_OUTPUT/output.py", line 182, in convert_model
    return super().convert_model(model, wanted_lorentz, wanted_coupling)
  File "/data/zwetters/modded5amc/madgraph/iolibs/export_cpp.py", line 2646, in convert_model
    model_builder.write_files()
  File "/data/zwetters/modded5amc/madgraph/iolibs/export_cpp.py", line 131, in write_files
    self.write_parameter_class_files()
  File "/data/zwetters/modded5amc/madgraph/iolibs/export_cpp.py", line 230, in write_parameter_class_files
    file_h, file_cc = self.generate_parameters_class_files()
  File "/data/zwetters/modded5amc/PLUGIN/CUDACPP_SA_OUTPUT/model_handling.py", line 842, in generate_parameters_class_files
    file_h, file_cc = self.super_generate_parameters_class_files()
  File "/data/zwetters/modded5amc/PLUGIN/CUDACPP_SA_OUTPUT/model_handling.py", line 821, in super_generate_parameters_class_files
    replace_dict['eftspecial2'] = """#else
KeyError: 'dcoupoutfptypev2'
```

**Comment by valassi** [comment]
Hi @zeniheisser thanks a lot. We clearly have a lot of work to do :-)
I would keep this one at very low priority for the moment - unless you tell me this is precisely one of the most interesting examples, eg for your work on reweighting and/or with Robert...

**Comment by zeniheisser** [comment]
@valassi, this is definitely not high priority -- but #614 is what the Vienna group is requesting, so I'm definitely going to look into that!

**Comment by valassi** [comment]
Hi @zeniheisser as discussed, it turns out that my recent patches for SUSY, HEFT and SMEFT fixed code generation for the process you suggested. So this #615 is fixed and can be closed.

I added more tests in PR #847. Note that the code builds and runs, but there are some wrong results (see #846) to be fixed.

**Comment by valassi** [comment]
Closing.
